#!/bin/bash
# runbox-service daemon
# chkconfig: 345 20 80
# description: runbox service daemon

DAEMON_PATH="/opt/runbox/server"

USERNAME=runbox

LOGFILE=/var/log/runbox/runbox-service.log
LOGERRFILE=/var/log/runbox/runbox-service.error.log

DAEMON=/opt/runbox/penv/bin/python
DAEMONOPTS="manage.py runserver -dR --port=5000 --threaded"

NAME=runbox-service
DESC="RunBox service"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
start)
	printf "%-50s" "Starting $NAME..."
	cd $DAEMON_PATH
	PID=`su --command="$DAEMON $DAEMONOPTS >>$LOGFILE 2>>$LOGERRFILE & echo \\\$!" $USERNAME`
	echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep | grep $DAEMON`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
	$0 stop
	$0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
